/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function Logo(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://sunnyisland.s3.us-east-2.amazonaws.com/media/glb/SunnyIslandLogo.glb')
  //const { nodes, materials } = useGLTF('/SunnyIslandLogo.glb')
  return (
    <group ref={group} {...props} scale={1.25} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials.PaletteMaterial003} />
    </group>
  )
}

useGLTF.preload('https://sunnyisland.s3.us-east-2.amazonaws.com/media/glb/SunnyIslandLogo.glb')
//useGLTF.preload('/SunnyIslandLogo.glb')