/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function YellowPepper(props) {
  const group = useRef()
 //const { nodes, materials } = useGLTF('/yellowPepper.glb')
  const { nodes, materials } = useGLTF('https://sunnyisland.s3.us-east-2.amazonaws.com/media/glb/yellowPepper.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.modelobj.geometry} material={nodes.modelobj.material} />
    </group>
  )
}



useGLTF.preload('https://sunnyisland.s3.us-east-2.amazonaws.com/media/glb/yellowPepper.glb')
//useGLTF.preload('/yellowPepper.glb')
